"""Phase 17 Automations

Revision ID: 503cc6a317d8
Revises: ed9f9367092b
Create Date: 2026-08-23 13:26:39.575030

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '503cc6a317d8'
down_revision: Union[str, None] = 'ed9f9367092b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('automation_type', sa.Enum('ONE_TIME', 'RECURRING', 'CRON', 'DELAY', 'CONDITION', name='automationtype'), nullable=False),
    sa.Column('schedule_definition', sa.JSON(), nullable=False),
    sa.Column('misfire_policy', sa.Enum('SKIP', 'CATCH_UP_ONCE', name='misfirepolicy'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('task_definition', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='automationstatus'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('automation_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_records_next_run_at'), 'automation_records', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_automation_records_principal_id'), 'automation_records', ['principal_id'], unique=False)
    op.create_table('conversation_records',
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('active_task_id', sa.String(length=64), nullable=True),
    sa.Column('active_plan_id', sa.String(length=64), nullable=True),
    sa.Column('pending_confirmation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversation_records_session_id'), 'conversation_records', ['session_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_keys_principal_id'), 'idempotency_keys', ['principal_id'], unique=False)
    op.create_table('long_term_memories',
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('normalized_content', sa.String(length=4096), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index(op.f('ix_long_term_memories_principal_id'), 'long_term_memories', ['principal_id'], unique=False)
    op.create_table('message_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('metadata_json', sa.String(length=2048), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_records_conversation_id'), 'message_records', ['conversation_id'], unique=False)
    op.create_table('automation_run_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('automation_id', sa.String(length=64), nullable=False),
    sa.Column('automation_version', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CLAIMED', 'SUBMITTED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'BLOCKED', 'EXPIRED', name='runstatus'), nullable=False),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_summary', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automation_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_automation_run_idempotency')
    )
    op.create_index(op.f('ix_automation_run_records_automation_id'), 'automation_run_records', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_run_records_claim_token'), 'automation_run_records', ['claim_token'], unique=False)
    op.create_index(op.f('ix_automation_run_records_scheduled_for'), 'automation_run_records', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_automation_run_records_status'), 'automation_run_records', ['status'], unique=False)
    op.add_column('task_records', sa.Column('principal_id', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_records', 'principal_id')
    op.drop_index(op.f('ix_automation_run_records_status'), table_name='automation_run_records')
    op.drop_index(op.f('ix_automation_run_records_scheduled_for'), table_name='automation_run_records')
    op.drop_index(op.f('ix_automation_run_records_claim_token'), table_name='automation_run_records')
    op.drop_index(op.f('ix_automation_run_records_automation_id'), table_name='automation_run_records')
    op.drop_table('automation_run_records')
    op.drop_index(op.f('ix_message_records_conversation_id'), table_name='message_records')
    op.drop_table('message_records')
    op.drop_index(op.f('ix_long_term_memories_principal_id'), table_name='long_term_memories')
    op.drop_table('long_term_memories')
    op.drop_index(op.f('ix_idempotency_keys_principal_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_conversation_records_session_id'), table_name='conversation_records')
    op.drop_table('conversation_records')
    op.drop_index(op.f('ix_automation_records_principal_id'), table_name='automation_records')
    op.drop_index(op.f('ix_automation_records_next_run_at'), table_name='automation_records')
    op.drop_table('automation_records')
    # ### end Alembic commands ###
