"""add_agents_tables

Revision ID: cf2eddeeb959
Revises: f7ff7562ee10
Create Date: 2026-08-25 03:05:55.645025

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cf2eddeeb959'
down_revision: Union[str, None] = 'f7ff7562ee10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('sender_agent_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_agent_id', sa.String(length=64), nullable=False),
    sa.Column('root_task_id', sa.String(length=64), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.String(length=4000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_agent_messages_recipient_agent_id'), 'agent_messages', ['recipient_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_root_task_id'), 'agent_messages', ['root_task_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_sender_agent_id'), 'agent_messages', ['sender_agent_id'], unique=False)
    op.create_table('agent_records',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('parent_agent_id', sa.String(length=64), nullable=True),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agent_records_execution_id'), 'agent_records', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_records_parent_agent_id'), 'agent_records', ['parent_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_records_state'), 'agent_records', ['state'], unique=False)
    op.create_index(op.f('ix_agent_records_task_id'), 'agent_records', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_records_task_id'), table_name='agent_records')
    op.drop_index(op.f('ix_agent_records_state'), table_name='agent_records')
    op.drop_index(op.f('ix_agent_records_parent_agent_id'), table_name='agent_records')
    op.drop_index(op.f('ix_agent_records_execution_id'), table_name='agent_records')
    op.drop_table('agent_records')
    op.drop_index(op.f('ix_agent_messages_sender_agent_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_root_task_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_recipient_agent_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    # ### end Alembic commands ###
